# Generated by Django 5.0.3 on 2024-04-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_category_options_rename_name_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=1950),
        ),
    ]
