# Generated by Django 5.0.3 on 2024-05-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movies_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='year',
        ),
    ]
