# Generated by Django 5.0.3 on 2024-05-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_alter_movies_user_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='movies',
        ),
    ]
