# Generated by Django 5.0.3 on 2024-06-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_rename_movie_review_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
